### ISSUE TITLE
Have better authentication checks

### ISSUE THREAD

**Issue by mdavoodi** [mohamicorp/crucible-review-hook#11]
> I recreated the application link and the link itself seems fine.  I did realize that I didn’t turn the crucible hook settings on for the repository though.  When I turned it on and tested it out, I now see the link where the review should be, but is says No Review and there’s a red exclamation icon that says “Review data not found”.  I found that this comment was in the pull request:
>  
> Crucible cannot authenticate your account.
> Click here to authenticate.
>  
> I clicked the link to authenticate, then recreated the pull request and the review was created.  So I think we’re back online.
>  
> Is there any way that you can catch that authentication error in the plug in and let the user handle it without needing to recreate the review?

The current authentication and application link system is very clunky. It would be nice to streamline this so users don't run into errors like this again.

**Comment by mdavoodi** [comment]
Related to #22

**Comment by AndreyLevchenko** [comment]
@mdavoodi 
with auth warning in plugin panel and re-create button it should be a bit more streamlined. Although I didn't found a way to load custome js on create pull request screen
![authenticate-link](https://user-images.githubusercontent.com/353652/27135927-a3eaa0e2-513b-11e7-96e3-d3e7ee802e3f.png)

also hook is disabled by default. Probably we should add some warning. Like search plugin has

**Comment by mdavoodi** [comment]
Fixed this in version 1.6.
