### ISSUE TITLE
Better formatted error messages

### ISSUE THREAD

**Issue by mdavoodi** [mohamicorp/crucible-review-hook#21]
Some of the error messages look ugly and aren't working that well with the new error API.

**Comment by AndreyLevchenko** [comment]
@mdavoodi 
can you add some screenshots here?

**Comment by mdavoodi** [comment]
![image](https://user-images.githubusercontent.com/2616497/27201597-1427cee2-51d3-11e7-8c01-2f4cfb0f0003.png)
This error message isn't super well formatted and easy to read. It get's the job done but it could look nicer.

**Comment by mdavoodi** [comment]
This is what a better formatted message looks like:
![image](https://user-images.githubusercontent.com/2616497/27201785-cae9f4de-51d3-11e7-98eb-ec595e79965e.png)

**Comment by mdavoodi** [comment]
We've addressed some of the concerns here, to go further we could make all error messages come in the same distinct format.
